[package]
name = "pijul-core"
description = "Core library of Pijul, a distributed version control system based on a sound theory of collaborative work."
version.workspace = true
repository.workspace = true
documentation = "https://docs.rs/pijul-core"
authors.workspace = true
edition.workspace = true
license = "GPL-2.0-or-later"
include = [
    "Cargo.toml",
    "src/lib.rs",
    "src/apply.rs",
    "src/change.rs",
    "src/find_alive.rs",
    "src/fs.rs",
    "src/key.rs",
    "src/missing_context.rs",
    "src/path.rs",
    "src/pin.rs",
    "src/record.rs",
    "src/small_string.rs",
    "src/text_encoding.rs",
    "src/vector2.rs",
    "src/vertex_buffer.rs",
    "src/alive/debug.rs",
    "src/alive/dfs.rs",
    "src/alive/mod.rs",
    "src/alive/output.rs",
    "src/alive/retrieve.rs",
    "src/alive/tarjan.rs",
    "src/apply/edge.rs",
    "src/apply/vertex.rs",
    "src/change/change_file.rs",
    "src/change/noenc.rs",
    "src/change/parse.rs",
    "src/change/printable.rs",
    "src/change/text_changes.rs",
    "src/changestore/filesystem.rs",
    "src/changestore/memory.rs",
    "src/changestore/mod.rs",
    "src/diff/algorithm.rs",
    "src/diff/bin.rs",
    "src/diff/delete.rs",
    "src/diff/mod.rs",
    "src/diff/replace.rs",
    "src/diff/split.rs",
    "src/diff/vertex_buffer.rs",
    "src/output/archive.rs",
    "src/output/mod.rs",
    "src/output/working_copy.rs",
    "src/pristine/block.rs",
    "src/pristine/change_id.rs",
    "src/pristine/edge.rs",
    "src/pristine/hash.rs",
    "src/pristine/inode.rs",
    "src/pristine/inode_metadata.rs",
    "src/pristine/inode_vertex.rs",
    "src/pristine/merkle.rs",
    "src/pristine/mod.rs",
    "src/pristine/patch_id.rs",
    "src/pristine/path_id.rs",
    "src/pristine/sanakirja.rs",
    "src/pristine/vertex.rs",
    "src/tag/txn.rs",
    "src/unrecord/mod.rs",
    "src/unrecord/working_copy.rs",
    "src/working_copy/filesystem.rs",
    "src/working_copy/memory.rs",
    "src/working_copy/mod.rs",
    "src/tests/add_file.rs",
    "src/tests/change.rs",
    "src/tests/clone.rs",
    "src/tests/conflict.rs",
    "src/tests/diff.rs",
    "src/tests/file_conflicts.rs",
    "src/tests/filesystem.rs",
    "src/tests/inode_symmetry.rs",
    "src/tests/missing_context.rs",
    "src/tests/mod.rs",
    "src/tests/partial.rs",
    "src/tests/patch.rs",
    "src/tests/performance.rs",
    "src/tests/record_parallel.rs",
    "src/tests/record_reads.rs",
    "src/tests/replaces.rs",
    "src/tests/rm_file.rs",
    "src/tests/rollback.rs",
    "src/tests/sub_root.rs",
    "src/tests/text.rs",
    "src/tests/text_changes.rs",
    "src/tests/unrecord.rs",
    "src/tests/data/1252-dos.1",
    "src/tests/data/1252-dos.2",
    "src/tests/data/1252.1",
    "src/tests/data/1252.2",
    "src/tests/data/8859-1.1",
    "src/tests/data/8859-1.2",
    "src/tests/data/gb.1",
    "src/tests/data/gb.2",
]

[features]
ondisk-repos = [
    "mmap",
    "zstd",
    "ignore",
    "canonical-path",
    "lru-cache",
    "tempfile",
    "path-slash",
]
mmap = ["sanakirja/mmap"]
zstd = ["zstd-seekable"]
text-changes = []
default = ["ondisk-repos", "text-changes", "git2"]
tarball = ["tar", "flate2"]

[dependencies]
pijul-macros.workspace = true

canonical-path = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
ignore = { workspace = true, optional = true }
lru-cache = { workspace = true, optional = true }
path-slash = { workspace = true, optional = true }
tar = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
zstd-seekable = { workspace = true, optional = true }

adler32.workspace = true
bincode.workspace = true
bitflags = { workspace = true, features = ["serde"] }
blake3.workspace = true
byteorder.workspace = true
chardetng.workspace = true
crossbeam-deque.workspace = true
curve25519-dalek = { workspace = true, features = ["serde"] }
data-encoding.workspace = true
diffs.workspace = true
encoding_rs.workspace = true
imara-diff.workspace = true
jiff.workspace = true
log.workspace = true
nom.workspace = true
parking_lot.workspace = true
rand.workspace = true
regex.workspace = true
sanakirja.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
toml.workspace = true
git2 = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }

[dev-dependencies]
anyhow.workspace = true
env_logger.workspace = true
quickcheck.workspace = true
rand_chacha.workspace = true
rand.workspace = true
