[package]
name = "pijul-interaction"
description = "Human friendly input/output (progress bars, passwords etc) for contexts such as terminals or GUIs"
version.workspace = true
authors = ["Finchie"]
edition.workspace = true
repository.workspace = true
license.workspace = true
include = [
    "Cargo.toml",
    "src/lib.rs",
    "src/progress/mod.rs",
    "src/progress/terminal.rs",
]

[dependencies]
indicatif.workspace = true
thiserror.workspace = true
