[package]
name = "pijul-config"
description = "Configuration for the pijul version control system"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
include = [
    "Cargo.toml",
    "src/author.rs",
    "src/defaults.toml",
    "src/error.rs",
    "src/global.rs",
    "src/hook.rs",
    "src/lib.rs",
    "src/local.rs",
    "src/remote.rs",
    "src/template.rs",
]

[dependencies]
pijul-core.workspace = true
serde.workspace = true
blake3.workspace = true
dialoguer = { workspace = true, features = ["editor"] }
thiserror.workspace = true
dirs-next.workspace = true
figment.workspace = true
log.workspace = true
toml.workspace = true
whoami.workspace = true

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true
